# -*- coding: utf-8 -*-
# Datos completos del Mundial 2026

TEAMS = {
    "Mexico": {
        "rank": 15, "rank_pts": 1681.03, "tier": 4, "odds_win": 9000, "odds_group": -125,
        "confederation": "CONCACAF", "home_continent": True,
        "coach": "Javier Aguirre", "captain": "Edson Alvarez",
        "avg_temp_home": 24, "altitude_home": 2240,
        "form_10": "WWD_LWW_DW_WL_", "form_streak": 0.6,
        "wc_history": "cuartos_1986_1970",
        "key_players": [
            ("Santiago Gimenez", 25, "AC Milan", "ST", 14, 4, "starter"),
            ("Raul Jimenez", 35, "Fulham", "ST", 8, 2, "impact"),
            ("Hirving Lozano", 30, "PSV", "LW", 6, 5, "starter"),
            ("Edson Alvarez", 28, "Fenerbahce", "CB/DM", 3, 2, "starter"),
            ("Luis Romo", 31, "Guadalajara", "CM", 4, 3, "starter"),
            ("Luis Chavez", 30, "Dynamo Moscow", "CM", 5, 4, "starter"),
            ("Cesar Montes", 29, "Lokomotiv", "CB", 1, 0, "starter"),
            ("Jorge Sanchez", 28, "PAOK", "RB", 1, 3, "starter"),
            ("Guillermo Ochoa", 40, "AEL Limassol", "GK", 0, 0, "bench"),
            ("Alexis Vega", 28, "Toluca", "LW", 7, 3, "starter"),
            ("Orbelin Pineda", 30, "AEK Athens", "CAM", 6, 5, "starter"),
            ("Johan Vasquez", 27, "Genoa", "CB", 0, 1, "starter"),
            ("Jesus Gallardo", 31, "Toluca", "LB", 1, 2, "starter"),
        ],
        "group_odds": -125, "goals_scored_avg": 1.8, "goals_conceded_avg": 0.9,
        "diaspora_in_usa": 37200000,
    },
    "South Korea": {
        "rank": 25, "rank_pts": 1588.66, "tier": 4, "odds_win": 40000, "odds_group": 350,
        "confederation": "AFC", "home_continent": False,
        "coach": "Hong Myungbo", "captain": "Son Heung-min",
        "avg_temp_home": 14, "altitude_home": 50,
        "form_10": "WDL_WW_LD_WW_L_", "form_streak": 0.5,
        "wc_history": "semifinal_2002",
        "key_players": [
            ("Son Heung-min", 33, "LAFC", "LW", 14, 6, "starter"),
            ("Kim Min-jae", 29, "Bayern Munich", "CB", 2, 1, "starter"),
            ("Lee Kang-in", 25, "PSG", "CAM", 6, 7, "starter"),
            ("Hwang Hee-chan", 30, "Wolves", "RW", 8, 4, "starter"),
            ("Hwang In-beom", 29, "Feyenoord", "CM", 3, 3, "starter"),
            ("Cho Gue-sung", 28, "Midtjylland", "ST", 9, 2, "starter"),
            ("Lee Jae-sung", 33, "Mainz", "CM", 4, 3, "starter"),
        ],
        "group_odds": 350, "goals_scored_avg": 1.6, "goals_conceded_avg": 1.0,
        "diaspora_in_usa": 1800000,
    },
    "South Africa": {
        "rank": 60, "rank_pts": 1429.73, "tier": 5, "odds_win": 100000, "odds_group": 1200,
        "confederation": "CAF", "home_continent": False,
        "coach": "Hugo Broos", "captain": "Ronwen Williams",
        "avg_temp_home": 22, "altitude_home": 1700,
        "form_10": "WWD_LW_LD_WD_W_", "form_streak": 0.5,
        "wc_history": "fase_grupos_1998_2002_2010",
        "key_players": [
            ("Percy Tau", 32, "Al Ahly", "FW", 8, 5, "starter"),
            ("Lyle Foster", 25, "Burnley", "ST", 6, 2, "starter"),
            ("Teboho Mokoena", 29, "Mamelodi Sundowns", "CM", 4, 4, "starter"),
            ("Ronwen Williams", 34, "Mamelodi Sundowns", "GK", 0, 0, "starter"),
            ("Khuliso Mudau", 31, "Mamelodi Sundowns", "RB", 1, 3, "starter"),
        ],
        "group_odds": 1200, "goals_scored_avg": 1.2, "goals_conceded_avg": 1.1,
        "diaspora_in_usa": 102000,
    },
    "Czechia": {
        "rank": 41, "rank_pts": 1501.38, "tier": 5, "odds_win": 50000, "odds_group": 350,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Miroslav Koubek", "captain": "Ladislav Krejci",
        "avg_temp_home": 10, "altitude_home": 250,
        "form_10": "WLW_DL_WD_WL_W_", "form_streak": 0.45,
        "wc_history": "final_1934_1962",
        "key_players": [
            ("Patrik Schick", 30, "Bayer Leverkusen", "ST", 12, 4, "starter"),
            ("Tomas Soucek", 31, "West Ham", "CM", 5, 2, "starter"),
            ("Ladislav Krejci", 27, "Wolves", "CB", 1, 1, "starter"),
            ("Vladimir Coufal", 33, "Hoffenheim", "RB", 0, 3, "starter"),
            ("Adam Hlozek", 23, "Hoffenheim", "LW", 6, 5, "starter"),
            ("Pavel Sulc", 25, "Lyon", "CAM", 5, 4, "starter"),
        ],
        "group_odds": 350, "goals_scored_avg": 1.5, "goals_conceded_avg": 1.2,
        "diaspora_in_usa": 210000,
    },
    "Canada": {
        "rank": 30, "rank_pts": 1556.48, "tier": 5, "odds_win": 20000, "odds_group": 200,
        "confederation": "CONCACAF", "home_continent": True,
        "coach": "Jesse Marsch", "captain": "Alphonso Davies",
        "avg_temp_home": 6, "altitude_home": 100,
        "form_10": "WDL_WW_LW_DW_W_", "form_streak": 0.55,
        "wc_history": "fase_grupos_2022",
        "key_players": [
            ("Alphonso Davies", 25, "Bayern Munich", "LB/LW", 5, 7, "starter"),
            ("Jonathan David", 26, "Juventus", "ST", 15, 5, "starter"),
            ("Stephen Eustaquio", 29, "FC Porto", "CM", 4, 5, "starter"),
            ("Tajon Buchanan", 27, "Villarreal", "RW", 6, 4, "starter"),
            ("Cyle Larin", 31, "Mallorca", "ST", 8, 3, "starter"),
            ("Alistair Johnston", 27, "Celtic", "RB", 1, 2, "starter"),
            ("Ismael Kone", 24, "Sassuolo", "CM", 3, 3, "starter"),
        ],
        "group_odds": 200, "goals_scored_avg": 1.7, "goals_conceded_avg": 1.1,
        "diaspora_in_usa": 1050000,
    },
    "Switzerland": {
        "rank": 19, "rank_pts": 1649.40, "tier": 4, "odds_win": 6500, "odds_group": -135,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Murat Yakin", "captain": "Granit Xhaka",
        "avg_temp_home": 10, "altitude_home": 500,
        "form_10": "WDL_WW_LW_DW_D_", "form_streak": 0.55,
        "wc_history": "cuartos_1934_1938_1954",
        "key_players": [
            ("Granit Xhaka", 33, "Sunderland", "CM", 4, 6, "starter"),
            ("Manuel Akanji", 30, "Inter Milan", "CB", 2, 0, "starter"),
            ("Gregor Kobel", 28, "Dortmund", "GK", 0, 0, "starter"),
            ("Breel Embolo", 29, "Rennes", "ST", 10, 4, "starter"),
            ("Ricardo Rodriguez", 33, "Real Betis", "LB", 1, 2, "starter"),
            ("Denis Zakaria", 29, "Monaco", "CM", 3, 2, "squad"),
            ("Xherdan Shaqiri", 34, "Chicago Fire", "RW", 5, 4, "squad"),
        ],
        "group_odds": -135, "goals_scored_avg": 1.7, "goals_conceded_avg": 1.0,
        "diaspora_in_usa": 420000,
    },
    "Qatar": {
        "rank": 55, "rank_pts": 1454.96, "tier": 7, "odds_win": 150000, "odds_group": 3000,
        "confederation": "AFC", "home_continent": False,
        "coach": "Tintin Marquez", "captain": "Akram Afif",
        "avg_temp_home": 33, "altitude_home": 10,
        "form_10": "LDL_WW_LW_DL_W_", "form_streak": 0.4,
        "wc_history": "fase_grupos_2022",
        "key_players": [
            ("Akram Afif", 29, "Al Sadd", "LW", 12, 8, "starter"),
            ("Almoez Ali", 29, "Al Duhail", "ST", 10, 3, "starter"),
            ("Bassam Al-Rawi", 28, "Al Rayyan", "CB", 2, 1, "starter"),
        ],
        "group_odds": 3000, "goals_scored_avg": 1.3, "goals_conceded_avg": 1.6,
        "diaspora_in_usa": 28000,
    },
    "Bosnia & Herzegovina": {
        "rank": 71, "rank_pts": 1385.84, "tier": 6, "odds_win": 50000, "odds_group": 600,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Sergej Barbarez", "captain": "Edin Dzeko",
        "avg_temp_home": 12, "altitude_home": 500,
        "form_10": "LWL_WW_LD_WL_W_", "form_streak": 0.4,
        "wc_history": "fase_grupos_2014",
        "key_players": [
            ("Edin Dzeko", 40, "Schalke 04", "ST", 10, 3, "starter"),
            ("Sead Kolasinac", 32, "Atalanta", "LB", 1, 2, "starter"),
            ("Ermedin Demirovic", 28, "VfB Stuttgart", "ST", 8, 4, "starter"),
            ("Amar Dedic", 23, "Benfica", "RB", 1, 3, "starter"),
        ],
        "group_odds": 600, "goals_scored_avg": 1.4, "goals_conceded_avg": 1.5,
        "diaspora_in_usa": 300000,
    },
    "Brazil": {
        "rank": 6, "rank_pts": 1761.16, "tier": 2, "odds_win": 900, "odds_group": -350,
        "confederation": "CONMEBOL", "home_continent": False,
        "coach": "Carlo Ancelotti", "captain": "Marquinhos",
        "avg_temp_home": 26, "altitude_home": 100,
        "form_10": "WWL_DW_WL_WD_L_", "form_streak": 0.6,
        "wc_history": "campeon_1958_1962_1970_1994_2002",
        "key_players": [
            ("Vinicius Jr", 25, "Real Madrid", "LW", 16, 5, "starter"),
            ("Raphinha", 29, "Barcelona", "RW", 13, 3, "starter"),
            ("Neymar", 34, "Santos", "CAM", 7, 5, "impact"),
            ("Alisson", 33, "Liverpool", "GK", 0, 0, "starter"),
            ("Marquinhos", 32, "PSG", "CB", 2, 1, "starter"),
            ("Bruno Guimaraes", 28, "Newcastle", "CM", 5, 5, "starter"),
            ("Casemiro", 34, "Man United", "CDM", 1, 1, "starter"),
            ("Gabriel Martinelli", 24, "Arsenal", "LW", 6, 3, "squad"),
            ("Endrick", 19, "Lyon", "ST", 3, 1, "squad"),
            ("Matheus Cunha", 26, "Man United", "ST", 8, 4, "starter"),
            ("Gabriel Magalhaes", 28, "Arsenal", "CB", 3, 1, "starter"),
            ("Lucas Paqueta", 28, "Flamengo", "CAM", 5, 4, "starter"),
        ],
        "group_odds": -350, "goals_scored_avg": 2.1, "goals_conceded_avg": 0.8,
        "diaspora_in_usa": 1800000,
    },
    "Morocco": {
        "rank": 8, "rank_pts": 1755.87, "tier": 3, "odds_win": 5000, "odds_group": 400,
        "confederation": "CAF", "home_continent": False,
        "coach": "Mohamed Ouahbi", "captain": "Achraf Hakimi",
        "avg_temp_home": 22, "altitude_home": 400,
        "form_10": "WDW_LW_WW_DW_W_", "form_streak": 0.65,
        "wc_history": "semifinal_2022",
        "key_players": [
            ("Achraf Hakimi", 27, "PSG", "RB", 4, 6, "starter"),
            ("Brahim Diaz", 26, "Real Madrid", "CAM", 8, 5, "starter"),
            ("Yassine Bounou", 35, "Al-Hilal", "GK", 0, 0, "starter"),
            ("Noussair Mazraoui", 28, "Man United", "RB/LB", 1, 2, "starter"),
            ("Nayef Aguerd", 30, "Marseille", "CB", 1, 1, "starter"),
            ("Sofyan Amrabat", 29, "Real Betis", "DM", 1, 2, "starter"),
            ("Hakim Ziyech", 33, "Galatasaray", "RW", 5, 5, "starter"),
            ("Youssef En-Nesyri", 29, "Fenerbahce", "ST", 14, 3, "starter"),
            ("Bilal El Khannouss", 22, "Stuttgart", "MF", 4, 5, "key_creator"),
        ],
        "group_odds": 400, "goals_scored_avg": 1.6, "goals_conceded_avg": 0.9,
        "diaspora_in_usa": 690000,
    },
    "Scotland": {
        "rank": 43, "rank_pts": 1498.35, "tier": 5, "odds_win": 20000, "odds_group": 1000,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Steve Clarke", "captain": "Andy Robertson",
        "avg_temp_home": 8, "altitude_home": 50,
        "form_10": "DL_WW_LW_DW_WL_", "form_streak": 0.5,
        "wc_history": "fase_grupos_1954_1958_1974_1978_1982_1986_1990_1998",
        "key_players": [
            ("Andy Robertson", 32, "Liverpool", "LB", 2, 7, "starter"),
            ("Kieran Tierney", 29, "Celtic", "LB/CB", 1, 2, "starter"),
            ("Scott McTominay", 29, "Napoli", "CM", 7, 3, "starter"),
            ("John McGinn", 31, "Aston Villa", "CM", 5, 5, "starter"),
            ("Billy Gilmour", 25, "Napoli", "CM", 2, 4, "starter"),
            ("Che Adams", 29, "Torino", "ST", 8, 3, "starter"),
        ],
        "group_odds": 1000, "goals_scored_avg": 1.4, "goals_conceded_avg": 1.2,
        "diaspora_in_usa": 250000,
    },
    "Haiti": {
        "rank": 83, "rank_pts": 1291.71, "tier": 8, "odds_win": 250000, "odds_group": 12000,
        "confederation": "CONCACAF", "home_continent": True,
        "coach": "Sebastien Migne", "captain": "Johnny Placide",
        "avg_temp_home": 28, "altitude_home": 0,
        "form_10": "WDL_WL_LD_W_LW_", "form_streak": 0.35,
        "wc_history": "fase_grupos_1974",
        "key_players": [
            ("Derrick Etienne Jr", 29, "Toronto FC", "FW", 5, 3, "starter"),
            ("Duckens Nazon", 32, "", "ST", 6, 2, "starter"),
            ("Frantzdy Pierrot", 31, "", "ST", 4, 1, "starter"),
        ],
        "group_odds": 12000, "goals_scored_avg": 0.8, "goals_conceded_avg": 1.8,
        "diaspora_in_usa": 1050000,
    },
    "USA": {
        "rank": 16, "rank_pts": 1673.13, "tier": 3, "odds_win": 6000, "odds_group": 140,
        "confederation": "CONCACAF", "home_continent": True,
        "coach": "Mauricio Pochettino", "captain": "Christian Pulisic",
        "avg_temp_home": 13, "altitude_home": 200,
        "form_10": "WWL_WW_WW_DW_W_", "form_streak": 0.65,
        "wc_history": "semifinal_1930",
        "key_players": [
            ("Christian Pulisic", 27, "AC Milan", "LW", 8, 5, "starter"),
            ("Weston McKennie", 27, "Juventus", "CM", 4, 3, "starter"),
            ("Tyler Adams", 27, "Bournemouth", "CDM", 1, 2, "starter"),
            ("Gio Reyna", 23, "Dortmund", "CAM", 3, 4, "starter"),
            ("Folarin Balogun", 25, "Monaco", "ST", 9, 3, "starter"),
            ("Antonee Robinson", 28, "Fulham", "LB", 1, 3, "starter"),
            ("Sergino Dest", 25, "PSV", "RB", 1, 4, "starter"),
        ],
        "group_odds": 140, "goals_scored_avg": 1.9, "goals_conceded_avg": 0.9,
        "diaspora_in_usa": 0,
    },
    "Paraguay": {
        "rank": 40, "rank_pts": 1503.50, "tier": 5, "odds_win": 30000, "odds_group": 400,
        "confederation": "CONMEBOL", "home_continent": False,
        "coach": "Daniel Garnero", "captain": "Gustavo Gomez",
        "avg_temp_home": 25, "altitude_home": 100,
        "form_10": "WDL_WL_LW_WD_L_", "form_streak": 0.45,
        "wc_history": "cuartos_2010",
        "key_players": [
            ("Miguel Almiron", 32, "Newcastle", "LW", 6, 4, "starter"),
            ("Julio Enciso", 22, "Brighton", "CAM", 4, 3, "starter"),
            ("Antony Silva", 42, "", "GK", 0, 0, "starter"),
        ],
        "group_odds": 400, "goals_scored_avg": 1.3, "goals_conceded_avg": 1.1,
        "diaspora_in_usa": 690000,
    },
    "Australia": {
        "rank": 27, "rank_pts": 1580.67, "tier": 5, "odds_win": 60000, "odds_group": 800,
        "confederation": "AFC", "home_continent": False,
        "coach": "Graham Arnold", "captain": "Mathew Ryan",
        "avg_temp_home": 22, "altitude_home": 50,
        "form_10": "WDL_WL_WW_LD_W_", "form_streak": 0.5,
        "wc_history": "octavos_2006_2022",
        "key_players": [
            ("Jackson Irvine", 33, "St. Pauli", "CM", 5, 4, "starter"),
            ("Mathew Ryan", 34, "", "GK", 0, 0, "starter"),
            ("Ajdin Hrustic", 29, "", "CAM", 3, 3, "starter"),
            ("Nestory Irankunda", 20, "Bayern Munich", "RW", 3, 2, "young"),
        ],
        "group_odds": 800, "goals_scored_avg": 1.5, "goals_conceded_avg": 1.2,
        "diaspora_in_usa": 98000,
    },
    "Turkey": {
        "rank": 22, "rank_pts": 1599.04, "tier": 4, "odds_win": 9000, "odds_group": 175,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Vincenzo Montella", "captain": "Hakan Calhanoglu",
        "avg_temp_home": 15, "altitude_home": 100,
        "form_10": "WWL_WL_DW_WW_L_", "form_streak": 0.55,
        "wc_history": "semifinal_2002",
        "key_players": [
            ("Arda Guler", 21, "Real Madrid", "CAM", 7, 5, "starter"),
            ("Hakan Calhanoglu", 32, "Inter", "CM", 6, 8, "starter"),
            ("Kenan Yildiz", 21, "Juventus", "LW", 5, 4, "starter"),
            ("Orkun Kokcu", 25, "Benfica", "CM", 4, 5, "starter"),
        ],
        "group_odds": 175, "goals_scored_avg": 1.8, "goals_conceded_avg": 1.1,
        "diaspora_in_usa": 550000,
    },
    "Germany": {
        "rank": 10, "rank_pts": 1730.37, "tier": 2, "odds_win": 1400, "odds_group": -250,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Julian Nagelsmann", "captain": "Ilkay Gundogan",
        "avg_temp_home": 10, "altitude_home": 100,
        "form_10": "WWW_DW_WW_DW_W_", "form_streak": 0.70,
        "wc_history": "campeon_1954_1974_1990_2014",
        "key_players": [
            ("Jamal Musiala", 23, "Bayern Munich", "CAM", 3, 4, "starter"),
            ("Florian Wirtz", 23, "Liverpool", "CAM", 5, 3, "starter"),
            ("Kai Havertz", 26, "Arsenal", "ST", 8, 4, "starter"),
            ("Ilkay Gundogan", 35, "Man City", "CM", 4, 4, "starter"),
            ("Antonio Rudiger", 33, "Real Madrid", "CB", 2, 0, "starter"),
            ("Joshua Kimmich", 31, "Bayern Munich", "CM/RB", 3, 8, "starter"),
            ("Leroy Sane", 30, "Bayern Munich", "RW", 6, 5, "starter"),
            ("Marc ter Stegen", 34, "Barcelona", "GK", 0, 0, "starter"),
        ],
        "group_odds": -250, "goals_scored_avg": 2.4, "goals_conceded_avg": 0.6,
        "diaspora_in_usa": 1600000,
    },
    "Ecuador": {
        "rank": 23, "rank_pts": 1594.78, "tier": 4, "odds_win": 8000, "odds_group": 370,
        "confederation": "CONMEBOL", "home_continent": False,
        "coach": "Felix Sanchez", "captain": "Enner Valencia",
        "avg_temp_home": 22, "altitude_home": 2850,
        "form_10": "WDL_WW_LW_DW_W_", "form_streak": 0.55,
        "wc_history": "octavos_2006_2022",
        "key_players": [
            ("Moises Caicedo", 24, "Chelsea", "CM", 3, 3, "starter"),
            ("Willian Pacho", 24, "PSG", "CB", 1, 1, "starter"),
            ("Enner Valencia", 36, "", "ST", 8, 2, "starter"),
            ("Piero Hincapie", 24, "Bayer Leverkusen", "LB", 1, 3, "starter"),
            ("Kendry Paez", 19, "", "CAM", 4, 3, "young"),
        ],
        "group_odds": 370, "goals_scored_avg": 1.6, "goals_conceded_avg": 1.0,
        "diaspora_in_usa": 620000,
    },
    "Ivory Coast": {
        "rank": 37, "rank_pts": 1532.98, "tier": 5, "odds_win": 25000, "odds_group": 600,
        "confederation": "CAF", "home_continent": False,
        "coach": "Emerse Fae", "captain": "Franck Kessie",
        "avg_temp_home": 28, "altitude_home": 50,
        "form_10": "WLD_WW_LW_WD_W_", "form_streak": 0.55,
        "wc_history": "fase_grupos_2006_2010_2014_2022",
        "key_players": [
            ("Amad Diallo", 24, "Man United", "RW", 7, 5, "starter"),
            ("Sebastien Haller", 32, "", "ST", 9, 3, "starter"),
            ("Franck Kessie", 29, "", "CM", 5, 4, "starter"),
            ("Wilfried Zaha", 33, "", "LW", 6, 4, "starter"),
            ("Seko Fofana", 31, "", "CM", 4, 3, "starter"),
        ],
        "group_odds": 600, "goals_scored_avg": 1.5, "goals_conceded_avg": 1.1,
        "diaspora_in_usa": 215000,
    },
    "Curacao": {
        "rank": 81, "rank_pts": 1294.65, "tier": 8, "odds_win": 250000, "odds_group": 12000,
        "confederation": "CONCACAF", "home_continent": True,
        "coach": "Dick Advocaat", "captain": "Leandro Bacuna",
        "avg_temp_home": 28, "altitude_home": 0,
        "form_10": "LDL_WL_LW_LD_W_", "form_streak": 0.3,
        "wc_history": "debut",
        "key_players": [
            ("Leandro Bacuna", 34, "", "CM", 3, 3, "starter"),
            ("Juninho Bacuna", 28, "", "CM", 4, 2, "starter"),
            ("Cuco Martina", 36, "", "CB", 1, 0, "starter"),
        ],
        "group_odds": 12000, "goals_scored_avg": 0.7, "goals_conceded_avg": 2.0,
        "diaspora_in_usa": 180000,
    },
    "Netherlands": {
        "rank": 7, "rank_pts": 1757.87, "tier": 3, "odds_win": 2000, "odds_group": -125,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Ronald Koeman", "captain": "Virgil van Dijk",
        "avg_temp_home": 10, "altitude_home": 10,
        "form_10": "WWD_LW_WW_DW_W_", "form_streak": 0.6,
        "wc_history": "final_1974_1978_2010",
        "key_players": [
            ("Virgil van Dijk", 35, "Liverpool", "CB", 3, 1, "starter"),
            ("Frenkie de Jong", 29, "Barcelona", "CM", 2, 3, "starter"),
            ("Cody Gakpo", 27, "Liverpool", "LW", 7, 4, "starter"),
            ("Xavi Simons", 23, "RB Leipzig", "CAM", 6, 7, "starter"),
            ("Tijjani Reijnders", 27, "AC Milan", "CM", 5, 4, "starter"),
            ("Memphis Depay", 32, "Atletico Madrid", "ST", 6, 3, "starter"),
            ("Matthijs de Ligt", 26, "Man United", "CB", 1, 0, "starter"),
        ],
        "group_odds": -125, "goals_scored_avg": 2.0, "goals_conceded_avg": 0.8,
        "diaspora_in_usa": 420000,
    },
    "Japan": {
        "rank": 18, "rank_pts": 1660.43, "tier": 3, "odds_win": 6500, "odds_group": 275,
        "confederation": "AFC", "home_continent": False,
        "coach": "Hajime Moriyasu", "captain": "Wataru Endo",
        "avg_temp_home": 16, "altitude_home": 50,
        "form_10": "WWD_LD_WW_LW_W_", "form_streak": 0.55,
        "wc_history": "octavos_2002_2010_2018_2022",
        "key_players": [
            ("Wataru Endo", 33, "Liverpool", "DM", 2, 1, "starter"),
            ("Takefusa Kubo", 25, "Real Sociedad", "RW", 5, 4, "starter"),
            ("Kaoru Mitoma", 29, "Brighton", "LW", 5, 5, "starter"),
            ("Ritsu Doan", 28, "", "RW", 4, 3, "starter"),
            ("Takehiro Tomiyasu", 27, "Arsenal", "CB/RB", 1, 0, "starter"),
        ],
        "group_odds": 275, "goals_scored_avg": 1.7, "goals_conceded_avg": 0.9,
        "diaspora_in_usa": 780000,
    },
    "Sweden": {
        "rank": 42, "rank_pts": 1514.77, "tier": 4, "odds_win": 12000, "odds_group": 450,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Jon Dahl Tomasson", "captain": "Victor Lindelof",
        "avg_temp_home": 6, "altitude_home": 10,
        "form_10": "WDL_WW_LD_WL_W_", "form_streak": 0.5,
        "wc_history": "final_1958",
        "key_players": [
            ("Viktor Gyokeres", 28, "Arsenal", "ST", 18, 6, "starter"),
            ("Alexander Isak", 26, "Newcastle", "ST", 12, 5, "starter"),
            ("Emil Forsberg", 34, "RB Leipzig", "CAM", 5, 6, "starter"),
            ("Dejan Kulusevski", 26, "Tottenham", "RW", 5, 7, "starter"),
            ("Victor Lindelof", 31, "Man United", "CB", 1, 0, "starter"),
        ],
        "group_odds": 450, "goals_scored_avg": 1.8, "goals_conceded_avg": 1.1,
        "diaspora_in_usa": 450000,
    },
    "Tunisia": {
        "rank": 47, "rank_pts": 1483.05, "tier": 6, "odds_win": 50000, "odds_group": 1200,
        "confederation": "CAF", "home_continent": False,
        "coach": "Kais Yaacoubi", "captain": "Youssef Msakni",
        "avg_temp_home": 25, "altitude_home": 10,
        "form_10": "WDL_LW_WD_LW_D_", "form_streak": 0.45,
        "wc_history": "fase_grupos_1978_1998_2002_2006_2018_2022",
        "key_players": [
            ("Ellyes Skhiri", 31, "", "CM", 4, 2, "starter"),
            ("Youssef Msakni", 35, "", "LW", 6, 3, "starter"),
            ("Wahbi Khazri", 35, "", "CAM", 4, 4, "starter"),
            ("Hannibal Mejbri", 23, "", "CM", 2, 3, "starter"),
        ],
        "group_odds": 1200, "goals_scored_avg": 1.2, "goals_conceded_avg": 1.3,
        "diaspora_in_usa": 135000,
    },
    "Belgium": {
        "rank": 9, "rank_pts": 1734.71, "tier": 3, "odds_win": 4000, "odds_group": -220,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Domenico Tedesco", "captain": "Kevin De Bruyne",
        "avg_temp_home": 10, "altitude_home": 50,
        "form_10": "WWD_LW_WL_DW_W_", "form_streak": 0.55,
        "wc_history": "semifinal_2018",
        "key_players": [
            ("Kevin De Bruyne", 35, "Man City", "CM", 6, 9, "starter"),
            ("Romelu Lukaku", 33, "Napoli", "ST", 11, 3, "starter"),
            ("Thibaut Courtois", 34, "Real Madrid", "GK", 0, 0, "starter"),
            ("Youri Tielemans", 30, "Aston Villa", "CM", 4, 5, "starter"),
            ("Leandro Trossard", 31, "Arsenal", "LW", 6, 6, "starter"),
            ("Jeremy Doku", 26, "Man City", "RW", 3, 5, "starter"),
            ("Amadou Onana", 25, "Aston Villa", "DM", 3, 2, "starter"),
        ],
        "group_odds": -220, "goals_scored_avg": 1.9, "goals_conceded_avg": 0.9,
        "diaspora_in_usa": 380000,
    },
    "Egypt": {
        "rank": 29, "rank_pts": 1563.24, "tier": 5, "odds_win": 30000, "odds_group": 400,
        "confederation": "CAF", "home_continent": False,
        "coach": "Hossam Hassan", "captain": "Mohamed Salah",
        "avg_temp_home": 28, "altitude_home": 50,
        "form_10": "WWD_LW_WW_DW_W_", "form_streak": 0.6,
        "wc_history": "octavos_1934",
        "key_players": [
            ("Mohamed Salah", 34, "Liverpool", "RW", 18, 10, "starter"),
            ("Mohamed Elneny", 34, "", "CM", 2, 2, "starter"),
            ("Mahmoud Trezeguet", 31, "", "LW", 5, 3, "starter"),
        ],
        "group_odds": 400, "goals_scored_avg": 1.6, "goals_conceded_avg": 1.0,
        "diaspora_in_usa": 255000,
    },
    "Iran": {
        "rank": 21, "rank_pts": 1615.30, "tier": 5, "odds_win": 70000, "odds_group": 650,
        "confederation": "AFC", "home_continent": False,
        "coach": "Amir Ghalenoei", "captain": "Ehsan Hajsafi",
        "avg_temp_home": 22, "altitude_home": 1100,
        "form_10": "WDL_WW_LW_DW_L_", "form_streak": 0.5,
        "wc_history": "fase_grupos_1978_1998_2006_2014_2018_2022",
        "key_players": [
            ("Mehdi Taremi", 33, "Inter", "ST", 10, 5, "starter"),
            ("Alireza Jahanbakhsh", 32, "", "RW", 4, 3, "starter"),
            ("Sardar Azmoun", 31, "", "ST", 7, 3, "starter"),
        ],
        "group_odds": 650, "goals_scored_avg": 1.4, "goals_conceded_avg": 1.2,
        "diaspora_in_usa": 520000,
    },
    "New Zealand": {
        "rank": 85, "rank_pts": 1281.57, "tier": 7, "odds_win": 150000, "odds_group": 2000,
        "confederation": "OFC", "home_continent": False,
        "coach": "Darren Bazeley", "captain": "Chris Wood",
        "avg_temp_home": 14, "altitude_home": 50,
        "form_10": "WDL_WL_WW_LD_W_", "form_streak": 0.5,
        "wc_history": "fase_grupos_1982_2010",
        "key_players": [
            ("Chris Wood", 34, "Nottm Forest", "ST", 12, 3, "starter"),
            ("Liberato Cacace", 25, "Empoli", "LB", 1, 2, "starter"),
        ],
        "group_odds": 2000, "goals_scored_avg": 1.3, "goals_conceded_avg": 1.5,
        "diaspora_in_usa": 58000,
    },
    "Spain": {
        "rank": 2, "rank_pts": 1876.40, "tier": 1, "odds_win": 450, "odds_group": -475,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Luis de la Fuente", "captain": "Rodri",
        "avg_temp_home": 17, "altitude_home": 650,
        "form_10": "WWW_WW_DW_WD_D_", "form_streak": 0.75,
        "wc_history": "campeon_2010",
        "key_players": [
            ("Lamine Yamal", 19, "Barcelona", "RW", 16, 11, "starter"),
            ("Rodri", 30, "Man City", "DM", 1, 0, "starter"),
            ("Pedri", 23, "Barcelona", "CM", 2, 9, "starter"),
            ("Nico Williams", 24, "Athletic Bilbao", "LW", 6, 3, "starter"),
            ("Dani Olmo", 28, "Barcelona", "CAM", 7, 4, "starter"),
            ("Alvaro Morata", 33, "Atletico Madrid", "ST", 8, 3, "starter"),
            ("Unai Simon", 29, "Athletic Bilbao", "GK", 0, 0, "starter"),
            ("Marc Cucurella", 27, "Chelsea", "LB", 1, 3, "starter"),
        ],
        "group_odds": -475, "goals_scored_avg": 2.2, "goals_conceded_avg": 0.6,
        "diaspora_in_usa": 550000,
    },
    "Uruguay": {
        "rank": 17, "rank_pts": 1673.07, "tier": 3, "odds_win": 6500, "odds_group": 400,
        "confederation": "CONMEBOL", "home_continent": False,
        "coach": "Marcelo Bielsa", "captain": "Federico Valverde",
        "avg_temp_home": 22, "altitude_home": 50,
        "form_10": "WWL_DW_LW_WD_W_", "form_streak": 0.6,
        "wc_history": "campeon_1930_1950",
        "key_players": [
            ("Federico Valverde", 27, "Real Madrid", "CM", 5, 6, "starter"),
            ("Darwin Nunez", 27, "Liverpool", "ST", 13, 5, "starter"),
            ("Ronald Araujo", 27, "Barcelona", "CB", 2, 0, "starter"),
            ("Facundo Pellistri", 24, "", "RW", 3, 4, "starter"),
            ("Manuel Ugarte", 25, "Man United", "DM", 1, 2, "starter"),
        ],
        "group_odds": 400, "goals_scored_avg": 1.8, "goals_conceded_avg": 0.9,
        "diaspora_in_usa": 230000,
    },
    "Saudi Arabia": {
        "rank": 61, "rank_pts": 1421.43, "tier": 7, "odds_win": 100000, "odds_group": 3000,
        "confederation": "AFC", "home_continent": False,
        "coach": "Roberto Mancini", "captain": "Salem Al-Dawsari",
        "avg_temp_home": 33, "altitude_home": 10,
        "form_10": "WDL_LW_LD_WL_W_", "form_streak": 0.4,
        "wc_history": "octavos_1994",
        "key_players": [
            ("Salem Al-Dawsari", 34, "Al-Hilal", "LW", 8, 5, "starter"),
            ("Feras Al-Brikan", 26, "", "ST", 7, 3, "starter"),
        ],
        "group_odds": 3000, "goals_scored_avg": 1.1, "goals_conceded_avg": 1.5,
        "diaspora_in_usa": 112000,
    },
    "Cape Verde": {
        "rank": 67, "rank_pts": 1366.13, "tier": 8, "odds_win": 100000, "odds_group": 6000,
        "confederation": "CAF", "home_continent": False,
        "coach": "Bubista", "captain": "Ryan Mendes",
        "avg_temp_home": 25, "altitude_home": 10,
        "form_10": "WDL_WL_WL_DW_L_", "form_streak": 0.4,
        "wc_history": "debut",
        "key_players": [
            ("Ryan Mendes", 36, "", "LW", 5, 3, "starter"),
            ("Garry Rodrigues", 35, "", "RW", 4, 3, "starter"),
            ("Jamiro Monteiro", 32, "", "CM", 3, 4, "starter"),
        ],
        "group_odds": 6000, "goals_scored_avg": 0.9, "goals_conceded_avg": 1.6,
        "diaspora_in_usa": 45000,
    },
    "France": {
        "rank": 1, "rank_pts": 1877.32, "tier": 1, "odds_win": 475, "odds_group": -215,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Didier Deschamps", "captain": "Kylian Mbappe",
        "avg_temp_home": 13, "altitude_home": 100,
        "form_10": "WWW_DW_WW_DW_L_", "form_streak": 0.75,
        "wc_history": "campeon_1998_2018",
        "key_players": [
            ("Kylian Mbappe", 27, "Real Madrid", "LW", 25, 5, "starter"),
            ("Ousmane Dembele", 29, "PSG", "RW", 12, 8, "starter"),
            ("William Saliba", 25, "Arsenal", "CB", 2, 1, "starter"),
            ("Michael Olise", 24, "Bayern Munich", "RW", 14, 18, "starter"),
            ("Aurelien Tchouameni", 26, "Real Madrid", "DM", 2, 2, "starter"),
            ("Dayot Upamecano", 27, "Bayern Munich", "CB", 1, 1, "starter"),
            ("Desire Doue", 22, "PSG", "LW", 5, 4, "squad"),
            ("Mike Maignan", 31, "AC Milan", "GK", 0, 0, "starter"),
            ("Jules Kounde", 27, "Barcelona", "RB/CB", 2, 3, "starter"),
            ("Theo Hernandez", 28, "AC Milan", "LB", 4, 5, "starter"),
        ],
        "group_odds": -215, "goals_scored_avg": 2.3, "goals_conceded_avg": 0.7,
        "diaspora_in_usa": 415000,
    },
    "Norway": {
        "rank": 37, "rank_pts": 1510.49, "tier": 4, "odds_win": 15000, "odds_group": 600,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Stale Solbakken", "captain": "Martin Odegaard",
        "avg_temp_home": 6, "altitude_home": 10,
        "form_10": "WWD_LW_WW_DW_W_", "form_streak": 0.6,
        "wc_history": "octavos_1938_1998",
        "key_players": [
            ("Erling Haaland", 25, "Man City", "ST", 27, 8, "starter"),
            ("Martin Odegaard", 27, "Arsenal", "CAM", 6, 7, "starter"),
            ("Alexander Sorloth", 30, "Atletico Madrid", "ST", 12, 4, "starter"),
        ],
        "group_odds": 275, "goals_scored_avg": 2.0, "goals_conceded_avg": 1.0,
        "diaspora_in_usa": 180000,
    },
    "Senegal": {
        "rank": 14, "rank_pts": 1688.99, "tier": 4, "odds_win": 9000, "odds_group": 750,
        "confederation": "CAF", "home_continent": False,
        "coach": "Pape Thiaw", "captain": "Sadio Mane",
        "avg_temp_home": 28, "altitude_home": 10,
        "form_10": "WWD_LW_WW_DW_L_", "form_streak": 0.55,
        "wc_history": "cuartos_2002",
        "key_players": [
            ("Sadio Mane", 34, "Al-Nassr", "LW", 10, 5, "starter"),
            ("Kalidou Koulibaly", 35, "Al-Hilal", "CB", 1, 0, "starter"),
            ("Edouard Mendy", 34, "", "GK", 0, 0, "starter"),
            ("Ismaila Sarr", 28, "", "RW", 6, 4, "starter"),
            ("Idrissa Gueye", 36, "", "CM", 2, 3, "starter"),
        ],
        "group_odds": 750, "goals_scored_avg": 1.5, "goals_conceded_avg": 1.0,
        "diaspora_in_usa": 250000,
    },
    "Iraq": {
        "rank": 58, "rank_pts": 1447.14, "tier": 7, "odds_win": 150000, "odds_group": 8000,
        "confederation": "AFC", "home_continent": False,
        "coach": "Jesus Casas", "captain": "Saad Natiq",
        "avg_temp_home": 28, "altitude_home": 50,
        "form_10": "WDL_LW_LD_WL_D_", "form_streak": 0.35,
        "wc_history": "fase_grupos_1986",
        "key_players": [
            ("Ayman Hussein", 30, "", "ST", 7, 2, "starter"),
            ("Ali Adnan", 32, "", "LB", 1, 2, "starter"),
        ],
        "group_odds": 8000, "goals_scored_avg": 1.0, "goals_conceded_avg": 1.5,
        "diaspora_in_usa": 210000,
    },
    "Argentina": {
        "rank": 3, "rank_pts": 1874.81, "tier": 1, "odds_win": 900, "odds_group": -265,
        "confederation": "CONMEBOL", "home_continent": False,
        "coach": "Lionel Scaloni", "captain": "Lionel Messi",
        "avg_temp_home": 17, "altitude_home": 50,
        "form_10": "WWW_WW_WW_WW_W_", "form_streak": 0.85,
        "wc_history": "campeon_1978_1986_2022",
        "key_players": [
            ("Lionel Messi", 39, "Inter Miami", "CAM", 14, 7, "starter"),
            ("Lautaro Martinez", 28, "Inter Milan", "ST", 17, 6, "starter"),
            ("Julian Alvarez", 26, "Atletico Madrid", "ST", 10, 5, "starter"),
            ("Enzo Fernandez", 25, "Chelsea", "CM", 3, 4, "starter"),
            ("Alexis Mac Allister", 27, "Liverpool", "CM", 5, 4, "starter"),
            ("Cristian Romero", 28, "Tottenham", "CB", 1, 0, "starter"),
            ("Emiliano Martinez", 33, "Aston Villa", "GK", 0, 0, "starter"),
            ("Rodrigo De Paul", 32, "Atletico Madrid", "CM", 3, 5, "starter"),
            ("Giovani Lo Celso", 30, "Real Betis", "CAM", 3, 3, "starter"),
            ("Nahuel Molina", 28, "", "RB", 1, 2, "starter"),
            ("Nicolas Otamendi", 38, "", "CB", 1, 0, "starter"),
        ],
        "group_odds": -265, "goals_scored_avg": 2.1, "goals_conceded_avg": 0.6,
        "diaspora_in_usa": 2300000,
    },
    "Algeria": {
        "rank": 28, "rank_pts": 1564.26, "tier": 5, "odds_win": 35000, "odds_group": 800,
        "confederation": "CAF", "home_continent": False,
        "coach": "Vladimir Petkovic", "captain": "Riyad Mahrez",
        "avg_temp_home": 28, "altitude_home": 100,
        "form_10": "WDL_WW_LW_DW_W_", "form_streak": 0.5,
        "wc_history": "octavos_2014",
        "key_players": [
            ("Riyad Mahrez", 35, "Al-Ahli", "RW", 8, 6, "starter"),
            ("Youcef Belaïli", 34, "", "LW", 5, 4, "starter"),
            ("Ismael Bennacer", 28, "AC Milan", "CM", 3, 4, "starter"),
        ],
        "group_odds": 800, "goals_scored_avg": 1.5, "goals_conceded_avg": 1.1,
        "diaspora_in_usa": 350000,
    },
    "Austria": {
        "rank": 24, "rank_pts": 1593.45, "tier": 4, "odds_win": 15000, "odds_group": 370,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Ralf Rangnick", "captain": "David Alaba",
        "avg_temp_home": 9, "altitude_home": 200,
        "form_10": "WDL_WW_LW_WD_L_", "form_streak": 0.5,
        "wc_history": "semifinal_1954",
        "key_players": [
            ("Marcel Sabitzer", 32, "Dortmund", "CM", 5, 4, "starter"),
            ("David Alaba", 34, "Real Madrid", "CB/LB", 1, 2, "starter"),
            ("Marko Arnautovic", 37, "", "ST", 7, 3, "starter"),
            ("Konrad Laimer", 29, "Bayern Munich", "CM", 3, 3, "starter"),
            ("Christoph Baumgartner", 26, "RB Leipzig", "CAM", 5, 4, "starter"),
        ],
        "group_odds": 370, "goals_scored_avg": 1.6, "goals_conceded_avg": 1.1,
        "diaspora_in_usa": 345000,
    },
    "Jordan": {
        "rank": 64, "rank_pts": 1391.45, "tier": 7, "odds_win": 250000, "odds_group": 5000,
        "confederation": "AFC", "home_continent": False,
        "coach": "Jamal Sellami", "captain": "Musa Al-Taamari",
        "avg_temp_home": 22, "altitude_home": 800,
        "form_10": "WDL_LW_LD_WL_D_", "form_streak": 0.35,
        "wc_history": "debut",
        "key_players": [
            ("Musa Al-Taamari", 29, "Rennes", "LW", 6, 4, "starter"),
            ("Ali Olwan", 27, "", "ST", 4, 2, "starter"),
        ],
        "group_odds": 5000, "goals_scored_avg": 1.0, "goals_conceded_avg": 1.5,
        "diaspora_in_usa": 95000,
    },
    "Portugal": {
        "rank": 5, "rank_pts": 1763.83, "tier": 2, "odds_win": 850, "odds_group": -200,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Roberto Martinez", "captain": "Cristiano Ronaldo",
        "avg_temp_home": 17, "altitude_home": 100,
        "form_10": "WWW_DW_LD_WD_D_", "form_streak": 0.65,
        "wc_history": "semifinal_1966_2006",
        "key_players": [
            ("Cristiano Ronaldo", 41, "Al-Nassr", "ST", 28, 2, "starter"),
            ("Bruno Fernandes", 31, "Man United", "CAM", 12, 11, "starter"),
            ("Bernardo Silva", 31, "Man City", "CM", 6, 7, "starter"),
            ("Joao Neves", 21, "PSG", "CM", 2, 3, "starter"),
            ("Vitinha", 26, "PSG", "CM", 5, 5, "starter"),
            ("Rafael Leao", 27, "AC Milan", "LW", 8, 7, "starter"),
            ("Ruben Dias", 29, "Man City", "CB", 1, 0, "starter"),
            ("Diogo Costa", 26, "Porto", "GK", 0, 0, "starter"),
            ("Joao Cancelo", 32, "Barcelona", "RB", 2, 4, "starter"),
            ("Nuno Mendes", 24, "PSG", "LB", 2, 3, "starter"),
        ],
        "group_odds": -200, "goals_scored_avg": 2.1, "goals_conceded_avg": 0.8,
        "diaspora_in_usa": 580000,
    },
    "Colombia": {
        "rank": 13, "rank_pts": 1693.09, "tier": 3, "odds_win": 4000, "odds_group": 200,
        "confederation": "CONMEBOL", "home_continent": False,
        "coach": "Nestor Lorenzo", "captain": "James Rodriguez",
        "avg_temp_home": 27, "altitude_home": 300,
        "form_10": "WWD_LW_WD_WW_D_", "form_streak": 0.6,
        "wc_history": "cuartos_2014",
        "key_players": [
            ("James Rodriguez", 34, "Minnesota Utd", "CAM", 6, 8, "starter"),
            ("Luis Diaz", 29, "Liverpool", "LW", 11, 5, "starter"),
            ("Jefferson Lerma", 31, "", "CM", 4, 3, "starter"),
            ("Jhon Arias", 28, "Fluminense", "RW", 5, 5, "starter"),
            ("Yerry Mina", 31, "", "CB", 2, 0, "starter"),
            ("Davinson Sanchez", 30, "", "CB", 1, 0, "starter"),
        ],
        "group_odds": 200, "goals_scored_avg": 1.8, "goals_conceded_avg": 0.9,
        "diaspora_in_usa": 1200000,
    },
    "Uzbekistan": {
        "rank": 52, "rank_pts": 1465.34, "tier": 7, "odds_win": 150000, "odds_group": 3500,
        "confederation": "AFC", "home_continent": False,
        "coach": "Srecko Katanec", "captain": "Eldor Shomurodov",
        "avg_temp_home": 16, "altitude_home": 400,
        "form_10": "WDL_WL_WW_LD_W_", "form_streak": 0.45,
        "wc_history": "debut",
        "key_players": [
            ("Abdukodir Khusanov", 22, "Man City", "CB", 1, 0, "starter"),
            ("Eldor Shomurodov", 31, "", "ST", 8, 4, "starter"),
            ("Oston Urunov", 25, "", "CAM", 4, 3, "starter"),
        ],
        "group_odds": 3500, "goals_scored_avg": 1.2, "goals_conceded_avg": 1.4,
        "diaspora_in_usa": 58000,
    },
    "DR Congo": {
        "rank": 48, "rank_pts": 1478.35, "tier": 6, "odds_win": 100000, "odds_group": 1400,
        "confederation": "CAF", "home_continent": False,
        "coach": "Sebastien Desabre", "captain": "Chancel Mbemba",
        "avg_temp_home": 27, "altitude_home": 400,
        "form_10": "WDL_LW_WL_DW_L_", "form_streak": 0.4,
        "wc_history": "fase_grupos_1974",
        "key_players": [
            ("Cedric Bakambu", 35, "Real Betis", "ST", 7, 3, "starter"),
            ("Yoane Wissa", 29, "Brentford", "LW", 8, 4, "starter"),
            ("Chancel Mbemba", 31, "Marseille", "CB", 1, 1, "starter"),
        ],
        "group_odds": 1400, "goals_scored_avg": 1.1, "goals_conceded_avg": 1.4,
        "diaspora_in_usa": 40000,
    },
    "England": {
        "rank": 4, "rank_pts": 1825.97, "tier": 1, "odds_win": 700, "odds_group": -280,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Thomas Tuchel", "captain": "Harry Kane",
        "avg_temp_home": 10, "altitude_home": 50,
        "form_10": "WWW_WW_WW_LD_L_", "form_streak": 0.75,
        "wc_history": "campeon_1966",
        "key_players": [
            ("Harry Kane", 32, "Bayern Munich", "ST", 36, 5, "starter"),
            ("Jude Bellingham", 23, "Real Madrid", "CAM", 6, 4, "starter"),
            ("Declan Rice", 27, "Arsenal", "DM", 4, 3, "starter"),
            ("Bukayo Saka", 24, "Arsenal", "RW", 7, 5, "starter"),
            ("Marcus Rashford", 28, "Aston Villa", "LW", 8, 4, "starter"),
            ("John Stones", 32, "Man City", "CB", 1, 1, "starter"),
            ("Reece James", 26, "Chelsea", "RB", 1, 2, "starter"),
            ("Jordan Pickford", 32, "Everton", "GK", 0, 0, "starter"),
            ("Marc Guehi", 25, "Crystal Palace", "CB", 2, 1, "starter"),
            ("Kobbie Mainoo", 21, "Man United", "CM", 3, 2, "starter"),
            ("Ollie Watkins", 30, "Aston Villa", "ST", 14, 9, "starter"),
            ("Anthony Gordon", 25, "Newcastle", "LW", 8, 6, "starter"),
        ],
        "group_odds": -280, "goals_scored_avg": 2.2, "goals_conceded_avg": 0.7,
        "diaspora_in_usa": 680000,
    },
    "Croatia": {
        "rank": 11, "rank_pts": 1717.07, "tier": 3, "odds_win": 9000, "odds_group": 320,
        "confederation": "UEFA", "home_continent": False,
        "coach": "Zlatko Dalic", "captain": "Luka Modric",
        "avg_temp_home": 13, "altitude_home": 100,
        "form_10": "WDL_WW_LW_DW_W_", "form_streak": 0.5,
        "wc_history": "final_2018, semifinal_2022",
        "key_players": [
            ("Luka Modric", 40, "AC Milan", "CM", 2, 4, "starter"),
            ("Mateo Kovacic", 32, "Man City", "CM", 2, 3, "starter"),
            ("Josko Gvardiol", 24, "Man City", "LB/CB", 4, 2, "starter"),
            ("Ivan Perisic", 37, "Hajduk Split", "LW", 4, 4, "starter"),
            ("Andrej Kramaric", 35, "", "ST", 6, 3, "starter"),
            ("Dominik Livakovic", 31, "", "GK", 0, 0, "starter"),
        ],
        "group_odds": 320, "goals_scored_avg": 1.6, "goals_conceded_avg": 1.0,
        "diaspora_in_usa": 245000,
    },
    "Ghana": {
        "rank": 72, "rank_pts": 1346.31, "tier": 6, "odds_win": 30000, "odds_group": 1100,
        "confederation": "CAF", "home_continent": False,
        "coach": "Otto Addo", "captain": "Thomas Partey",
        "avg_temp_home": 28, "altitude_home": 50,
        "form_10": "WDL_LW_LW_WD_L_", "form_streak": 0.4,
        "wc_history": "cuartos_2010",
        "key_players": [
            ("Mohammed Kudus", 25, "Tottenham", "CAM", 8, 5, "starter"),
            ("Antoine Semenyo", 26, "Bournemouth", "ST", 7, 3, "starter"),
            ("Thomas Partey", 33, "", "CM", 3, 3, "starter"),
            ("Inaki Williams", 32, "", "ST", 5, 4, "starter"),
        ],
        "group_odds": 1100, "goals_scored_avg": 1.3, "goals_conceded_avg": 1.4,
        "diaspora_in_usa": 235000,
    },
    "Panama": {
        "rank": 33, "rank_pts": 1540.64, "tier": 6, "odds_win": 100000, "odds_group": 4000,
        "confederation": "CONCACAF", "home_continent": True,
        "coach": "Thomas Christiansen", "captain": "Anibal Godoy",
        "avg_temp_home": 28, "altitude_home": 10,
        "form_10": "WDL_WL_LW_WD_L_", "form_streak": 0.4,
        "wc_history": "fase_grupos_2018",
        "key_players": [
            ("Adalberto Carrasquilla", 27, "Pumas", "CM", 4, 5, "starter"),
            ("Jose Fajardo", 32, "", "ST", 6, 2, "starter"),
            ("Yeltsin Tejada", 34, "", "CM", 3, 3, "starter"),
        ],
        "group_odds": 4000, "goals_scored_avg": 1.1, "goals_conceded_avg": 1.5,
        "diaspora_in_usa": 570000,
    },
}

VENUES = {
    "Mexico City": {
        "country": "Mexico", "stadium": "Estadio Azteca", "capacity": 83000, "roof": False,
        "avg_temp": 23, "humidity": "Moderate", "rain_risk": "Moderate", "altitude": 2240,
    },
    "Guadalajara": {
        "country": "Mexico", "stadium": "Estadio Akron", "capacity": 46000, "roof": False,
        "avg_temp": 26, "humidity": "Moderate", "rain_risk": "Moderate", "altitude": 1566,
    },
    "Monterrey": {
        "country": "Mexico", "stadium": "Estadio BBVA", "capacity": 53500, "roof": False,
        "avg_temp": 37, "humidity": "Moderate", "rain_risk": "Low", "altitude": 540,
    },
    "Toronto": {
        "country": "Canada", "stadium": "BMO Field", "capacity": 30000, "roof": False,
        "avg_temp": 27, "humidity": "Moderate", "rain_risk": "Moderate", "altitude": 100,
    },
    "Vancouver": {
        "country": "Canada", "stadium": "BC Place", "capacity": 54500, "roof": True,
        "avg_temp": 22, "humidity": "Low", "rain_risk": "Low", "altitude": 10,
    },
    "Los Angeles": {
        "country": "USA", "stadium": "SoFi Stadium", "capacity": 70240, "roof": True,
        "avg_temp": 27, "humidity": "Low", "rain_risk": "Very Low", "altitude": 30,
    },
    "San Francisco": {
        "country": "USA", "stadium": "Levi's Stadium", "capacity": 68500, "roof": False,
        "avg_temp": 18, "humidity": "Low", "rain_risk": "Low", "altitude": 20,
    },
    "Seattle": {
        "country": "USA", "stadium": "Lumen Field", "capacity": 69000, "roof": False,
        "avg_temp": 22, "humidity": "Low", "rain_risk": "Low", "altitude": 10,
    },
    "Dallas": {
        "country": "USA", "stadium": "AT&T Stadium", "capacity": 80000, "roof": True,
        "avg_temp": 37, "humidity": "Moderate", "rain_risk": "Low", "altitude": 180,
    },
    "Houston": {
        "country": "USA", "stadium": "NRG Stadium", "capacity": 71000, "roof": True,
        "avg_temp": 35, "humidity": "Very High", "rain_risk": "Moderate", "altitude": 30,
    },
    "Atlanta": {
        "country": "USA", "stadium": "Mercedes-Benz Stadium", "capacity": 71000, "roof": True,
        "avg_temp": 32, "humidity": "High", "rain_risk": "Moderate", "altitude": 300,
    },
    "Miami": {
        "country": "USA", "stadium": "Hard Rock Stadium", "capacity": 65000, "roof": False,
        "avg_temp": 32, "humidity": "Very High", "rain_risk": "High", "altitude": 10,
    },
    "New York": {
        "country": "USA", "stadium": "MetLife Stadium", "capacity": 82500, "roof": False,
        "avg_temp": 29, "humidity": "Moderate", "rain_risk": "Moderate", "altitude": 20,
    },
    "Boston": {
        "country": "USA", "stadium": "Gillette Stadium", "capacity": 65000, "roof": False,
        "avg_temp": 27, "humidity": "Moderate", "rain_risk": "Low", "altitude": 80,
    },
    "Philadelphia": {
        "country": "USA", "stadium": "Lincoln Financial Field", "capacity": 67594, "roof": False,
        "avg_temp": 29, "humidity": "Moderate", "rain_risk": "Low", "altitude": 20,
    },
    "Kansas City": {
        "country": "USA", "stadium": "Arrowhead Stadium", "capacity": 76416, "roof": False,
        "avg_temp": 31, "humidity": "Moderate", "rain_risk": "Moderate", "altitude": 260,
    },
}

CITY_COORDS = {
    "Mexico City": (19.4326, -99.1332),
    "Guadalajara": (20.6597, -103.3496),
    "Monterrey": (25.6866, -100.3161),
    "Toronto": (43.6532, -79.3832),
    "Vancouver": (49.2827, -123.1207),
    "Los Angeles": (34.0522, -118.2437),
    "San Francisco": (37.7749, -122.4194),
    "Seattle": (47.6062, -122.3321),
    "Dallas": (32.7767, -96.7970),
    "Houston": (29.7604, -95.3698),
    "Atlanta": (33.7490, -84.3880),
    "Miami": (25.7617, -80.1918),
    "New York": (40.7128, -74.0060),
    "Boston": (42.3601, -71.0589),
    "Philadelphia": (39.9526, -75.1652),
    "Kansas City": (39.0997, -94.5786),
    "Goleta": (34.4358, -119.8276),
    "Renton": (47.4829, -122.2171),
    "Sandy": (40.5917, -111.8841),
    "Tampa": (27.9478, -82.4584),
    "Alexandria": (38.8048, -77.0469),
    "Boca Raton": (26.3683, -80.1289),
    "Columbus": (39.9612, -82.9988),
    "Spokane": (47.6588, -117.4260),
    "Winston-Salem": (36.0999, -80.2442),
    "Nashville": (36.1627, -86.7816),
    "Portland": (45.5051, -122.6750),
    "Tijuana": (32.5149, -117.0382),
    "Greenbrier County": (37.8790, -80.4517),
    "San Diego": (32.7157, -117.1611),
    "Greensboro": (36.0726, -79.7920),
    "New Tecumseth": (44.0833, -79.7500),
    "Palm Beach Gardens": (26.8234, -80.1387),
    "Santa Barbara": (34.4208, -119.6982),
    "Austin": (30.2672, -97.7431),
    "Charlotte": (35.2271, -80.8431),
    "Pachuca": (20.1168, -98.7413),
    "Chattanooga": (35.0456, -85.3097),
    "Mesa": (33.4152, -111.8315),
    "Irvine": (33.6846, -117.8265),
    "Cancun": (21.1619, -86.8515),
}

BASE_CAMPS = {
    "Algeria": "Kansas City",
    "Argentina": "Kansas City",
    "Australia": "San Francisco",
    "Austria": "Goleta",
    "Belgium": "Renton",
    "Bosnia & Herzegovina": "Sandy",
    "Brazil": "New York",
    "Cape Verde": "Tampa",
    "Canada": "Vancouver",
    "Colombia": "Guadalajara",
    "DR Congo": "Houston",
    "Ivory Coast": "Philadelphia",
    "Croatia": "Alexandria",
    "Curacao": "Boca Raton",
    "Czechia": "Dallas",
    "Ecuador": "Columbus",
    "England": "Kansas City",
    "Egypt": "Spokane",
    "France": "Boston",
    "Germany": "Winston-Salem",
    "Ghana": "Boston",
    "Haiti": "New York",
    "Iran": "Tijuana",
    "Iraq": "Greenbrier County",
    "Japan": "Nashville",
    "Jordan": "Portland",
    "South Korea": "Guadalajara",
    "Mexico": "Mexico City",
    "Morocco": "New York",
    "Netherlands": "Kansas City",
    "New Zealand": "San Diego",
    "Norway": "Greensboro",
    "Panama": "New Tecumseth",
    "Paraguay": "San Francisco",
    "Portugal": "Palm Beach Gardens",
    "Qatar": "Santa Barbara",
    "Saudi Arabia": "Austin",
    "Scotland": "Charlotte",
    "Senegal": "New York",
    "South Africa": "Pachuca",
    "Spain": "Chattanooga",
    "Sweden": "Dallas",
    "Switzerland": "San Diego",
    "Tunisia": "Monterrey",
    "Turkey": "Mesa",
    "USA": "Irvine",
    "Uruguay": "Cancun",
    "Uzbekistan": "Atlanta",
}

GROUPS = {
    "A": ["Mexico", "South Africa", "South Korea", "Czechia"],
    "B": ["Canada", "Bosnia & Herzegovina", "Qatar", "Switzerland"],
    "C": ["Brazil", "Morocco", "Haiti", "Scotland"],
    "D": ["USA", "Paraguay", "Australia", "Turkey"],
    "E": ["Germany", "Ecuador", "Ivory Coast", "Curacao"],
    "F": ["Netherlands", "Japan", "Sweden", "Tunisia"],
    "G": ["Belgium", "Egypt", "Iran", "New Zealand"],
    "H": ["Spain", "Uruguay", "Saudi Arabia", "Cape Verde"],
    "I": ["France", "Senegal", "Iraq", "Norway"],
    "J": ["Argentina", "Algeria", "Austria", "Jordan"],
    "K": ["Portugal", "DR Congo", "Uzbekistan", "Colombia"],
    "L": ["England", "Croatia", "Ghana", "Panama"],
}

FIXTURES = [
    # Group A
    ("Mexico", "South Africa", "Mexico City", "2026-06-11", "21:00", "A"),
    ("South Korea", "Czechia", "Guadalajara", "2026-06-12", "04:00", "A"),
    ("South Korea", "South Africa", "Monterrey", "2026-06-17", "21:00", "A"),
    ("Mexico", "Czechia", "Guadalajara", "2026-06-18", "21:00", "A"),
    ("Mexico", "South Korea", "Mexico City", "2026-06-23", "21:00", "A"),
    ("Czechia", "South Africa", "Toronto", "2026-06-23", "21:00", "A"),
    # Group B
    ("Canada", "Bosnia & Herzegovina", "Toronto", "2026-06-12", "21:00", "B"),
    ("Qatar", "Switzerland", "San Francisco", "2026-06-13", "21:00", "B"),
    ("Canada", "Qatar", "Vancouver", "2026-06-18", "21:00", "B"),
    ("Switzerland", "Bosnia & Herzegovina", "New York", "2026-06-19", "21:00", "B"),
    ("Switzerland", "Canada", "Vancouver", "2026-06-23", "23:00", "B"),
    ("Bosnia & Herzegovina", "Qatar", "Toronto", "2026-06-24", "21:00", "B"),
    # Group C
    ("Brazil", "Morocco", "New York", "2026-06-13", "23:00", "C"),
    ("Haiti", "Scotland", "Boston", "2026-06-14", "02:00", "C"),
    ("Scotland", "Morocco", "Boston", "2026-06-19", "23:00", "C"),
    ("Brazil", "Haiti", "Miami", "2026-06-20", "18:00", "C"),
    ("Scotland", "Brazil", "Miami", "2026-06-24", "23:00", "C"),
    ("Morocco", "Haiti", "Atlanta", "2026-06-24", "21:00", "C"),
    # Group D
    ("USA", "Paraguay", "Los Angeles", "2026-06-13", "03:00", "D"),
    ("Australia", "Turkey", "Vancouver", "2026-06-14", "05:00", "D"),
    ("Paraguay", "Australia", "Kansas City", "2026-06-19", "19:00", "D"),
    ("USA", "Turkey", "Dallas", "2026-06-20", "18:00", "D"),
    ("USA", "Australia", "Seattle", "2026-06-25", "18:00", "D"),
    ("Turkey", "Paraguay", "Miami", "2026-06-25", "21:00", "D"),
    # Group E
    ("Germany", "Curacao", "Houston", "2026-06-14", "18:00", "E"),
    ("Ivory Coast", "Ecuador", "Atlanta", "2026-06-15", "01:00", "E"),
    ("Ecuador", "Germany", "Houston", "2026-06-20", "20:00", "E"),
    ("Curacao", "Ivory Coast", "Miami", "2026-06-21", "15:00", "E"),
    ("Ecuador", "Curacao", "New York", "2026-06-25", "21:00", "E"),
    ("Germany", "Ivory Coast", "Seattle", "2026-06-26", "18:00", "E"),
    # Group F
    ("Netherlands", "Japan", "Dallas", "2026-06-14", "21:00", "F"),
    ("Sweden", "Tunisia", "Seattle", "2026-06-15", "04:00", "F"),
    ("Japan", "Sweden", "Dallas", "2026-06-20", "15:00", "F"),
    ("Netherlands", "Tunisia", "Dallas", "2026-06-21", "15:00", "F"),
    ("Netherlands", "Sweden", "Vancouver", "2026-06-25", "21:00", "F"),
    ("Japan", "Tunisia", "Los Angeles", "2026-06-26", "18:00", "F"),
    # Group G
    ("Belgium", "Egypt", "Seattle", "2026-06-15", "15:00", "G"),
    ("Iran", "New Zealand", "Vancouver", "2026-06-15", "15:00", "G"),
    ("Belgium", "Iran", "Seattle", "2026-06-21", "22:00", "G"),
    ("Egypt", "New Zealand", "Vancouver", "2026-06-21", "22:00", "G"),
    ("Egypt", "Iran", "Seattle", "2026-06-26", "22:00", "G"),
    ("Belgium", "New Zealand", "Vancouver", "2026-06-26", "22:00", "G"),
    # Group H
    ("Spain", "Cape Verde", "Atlanta", "2026-06-15", "12:00", "H"),
    ("Uruguay", "Saudi Arabia", "Houston", "2026-06-16", "15:00", "H"),
    ("Spain", "Saudi Arabia", "Atlanta", "2026-06-21", "12:00", "H"),
    ("Uruguay", "Cape Verde", "Houston", "2026-06-21", "15:00", "H"),
    ("Uruguay", "Spain", "Guadalajara", "2026-06-26", "21:00", "H"),
    ("Cape Verde", "Saudi Arabia", "Houston", "2026-06-26", "21:00", "H"),
    # Group I
    ("France", "Iraq", "Kansas City", "2026-06-16", "15:00", "I"),
    ("Norway", "Senegal", "Los Angeles", "2026-06-16", "18:00", "I"),
    ("France", "Norway", "Los Angeles", "2026-06-22", "15:00", "I"),
    ("Senegal", "Iraq", "Kansas City", "2026-06-22", "15:00", "I"),
    ("France", "Senegal", "Kansas City", "2026-06-26", "18:00", "I"),
    ("Norway", "Iraq", "San Francisco", "2026-06-26", "20:00", "I"),
    # Group J
    ("Argentina", "Jordan", "Dallas", "2026-06-16", "21:00", "J"),
    ("Algeria", "Austria", "Kansas City", "2026-06-17", "15:00", "J"),
    ("Argentina", "Algeria", "Kansas City", "2026-06-22", "17:00", "J"),
    ("Austria", "Jordan", "Dallas", "2026-06-22", "21:00", "J"),
    ("Argentina", "Austria", "Philadelphia", "2026-06-26", "21:00", "J"),
    ("Jordan", "Algeria", "Kansas City", "2026-06-27", "15:00", "J"),
    # Group K
    ("Portugal", "Uzbekistan", "Miami", "2026-06-17", "15:00", "K"),
    ("DR Congo", "Colombia", "Miami", "2026-06-17", "18:00", "K"),
    ("Portugal", "DR Congo", "Miami", "2026-06-23", "15:00", "K"),
    ("Colombia", "Uzbekistan", "Miami", "2026-06-24", "15:00", "K"),
    ("Colombia", "Portugal", "Miami", "2026-06-27", "17:00", "K"),
    ("DR Congo", "Uzbekistan", "Atlanta", "2026-06-27", "19:30", "K"),
    # Group L
    ("England", "Panama", "New York", "2026-06-15", "18:00", "L"),
    ("Croatia", "Ghana", "Philadelphia", "2026-06-15", "18:00", "L"),
    ("England", "Croatia", "New York", "2026-06-21", "15:00", "L"),
    ("Ghana", "Panama", "Philadelphia", "2026-06-21", "15:00", "L"),
    ("England", "Ghana", "New York", "2026-06-27", "15:00", "L"),
    ("Croatia", "Panama", "Philadelphia", "2026-06-27", "17:00", "L"),
]

def get_team(name):
    return TEAMS[name]

def get_venue(name):
    return VENUES[name]

def get_group_teams(group):
    return GROUPS[group]

def get_group_fixtures(group):
    return [f for f in FIXTURES if f[5] == group]

# ── Enrich teams with scraped player data ──────────────────────────────

_FOREIGN_PCT_ESTIMATES = {
    "UEFA": 0.95, "CONMEBOL": 0.85, "CONCACAF": 0.80,
    "CAF": 0.88, "AFC": 0.65, "OFC": 0.70,
}

_FANBASE = {
    "Argentina": 8, "Brazil": 8, "England": 8,
    "France": 7, "Germany": 7, "Spain": 7,
    "Mexico": 6, "Portugal": 6, "Netherlands": 6,
    "USA": 5, "Belgium": 5, "Uruguay": 5,
    "Colombia": 5, "Japan": 5, "Croatia": 5,
    "South Korea": 4, "Turkey": 4, "Sweden": 4, "Norway": 4,
    "Switzerland": 3, "Austria": 3, "Morocco": 3,
    "Ghana": 3, "Egypt": 3, "Senegal": 3, "Ivory Coast": 3,
    "Algeria": 3, "Tunisia": 3, "Saudi Arabia": 2,
    "Qatar": 2, "Iraq": 2, "South Africa": 2,
    "Australia": 2, "Canada": 2, "Ecuador": 2,
    "Paraguay": 2, "Czechia": 2, "Scotland": 2,
    "Bosnia & Herzegovina": 2, "Iran": 2, "Jordan": 2,
    "Uzbekistan": 2, "DR Congo": 2, "Cape Verde": 1,
    "Curacao": 1, "Haiti": 1, "Panama": 1, "New Zealand": 1,
}

# Estimated total squad market values (millions €) for teams without player-level data
_MARKET_VALUE_ESTIMATES = {
    "France": 1100, "Argentina": 1000, "England": 950, "Spain": 900,
    "Brazil": 850, "Germany": 780, "Portugal": 650,
    "Netherlands": 550, "Belgium": 480, "Colombia": 380, "Morocco": 350, "USA": 350,
    "Norway": 320, "Mexico": 300, "Uruguay": 300, "Croatia": 300, "Japan": 280,
    "Switzerland": 250, "Turkey": 230, "Ecuador": 200, "Senegal": 200,
    "Sweden": 180, "Austria": 170, "Czechia": 150, "Canada": 140, "Scotland": 130,
    "South Korea": 120, "Ivory Coast": 120, "Egypt": 110, "Algeria": 100,
    "Iran": 90, "Australia": 80, "Paraguay": 80, "South Africa": 70,
    "Tunisia": 65, "Ghana": 60, "Bosnia & Herzegovina": 55, "DR Congo": 45,
    "Panama": 35, "Saudi Arabia": 30, "Qatar": 25, "Iraq": 20,
    "Uzbekistan": 18, "Jordan": 15, "New Zealand": 15,
    "Haiti": 10, "Cape Verde": 8, "Curacao": 5,
}

def _enrich_teams():
    import json, os
    players_path = os.path.join(os.path.dirname(__file__), "output", "players.json")
    if not os.path.exists(players_path):
        return

    with open(players_path, encoding="utf-8") as f:
        all_players = json.load(f)

    for name, team in TEAMS.items():
        squad = all_players.get(name, [])
        team["players"] = squad
        team["squad_size"] = len(squad)
        team.pop("key_players", None)

        if squad:
            ages = [p["age"] for p in squad]
            team["avg_age"] = sum(ages) / len(ages)

            mvs = [p.get("market_value") or 0 for p in squad]
            total_mv = sum(mvs)
            non_zero = [v for v in mvs if v > 0]
            if non_zero:
                team["market_value_total"] = total_mv
                team["market_value_avg"] = total_mv / len(non_zero)
            else:
                est = _MARKET_VALUE_ESTIMATES.get(name, 50)
                team["market_value_total"] = est
                team["market_value_avg"] = est / 26
        else:
            team["squad_size"] = 26
            team["avg_age"] = 27.0
            est = _MARKET_VALUE_ESTIMATES.get(name, 50)
            team["market_value_total"] = est
            team["market_value_avg"] = est / 26

        conf = team.get("confederation", "")
        team.setdefault("foreign_pct", _FOREIGN_PCT_ESTIMATES.get(conf, 0.8))
        team["global_fanbase"] = _FANBASE.get(name, 2)

_enrich_teams()
